config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
 sessions:      'admins/sessions',
 passwords:     'admins/passwords',
 registrations: 'admins/registrations'
 }
 devise_for :users, controllers: {
 sessions:      'users/sessions',
 passwords:     'users/passwords',
 registrations: 'users/registrations'
 }

  root 'tops#top'
  get 'tops/all_top' => 'tops#all_top'
  get 'tops/about' => 'tops#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only: [:show,:edit,:update,:destroy] do
  	member do
  		get :following, :followers, :mypage, :favorite_index, :blockeds, :blocking, :block_index
  	end
  end
  	resources :relationships, only: [:create,:destroy]
    resources :block_relationships, only: [:create,:destroy]
  	get 'tops/follow_top' => 'tops#follow_top'
  	get 'searches/search' => 'searches#search'
  	resources :posts, only: [:show,:edit,:new,:update,:create,:destroy] do
      member do
        get :tag_post_index, :favorite_user_index
      end
  		resources :favorites, only: [:create,:destroy]
  		resources :comments, only: [:create,:new,:destroy] do
        member do
          get :reply
          post :reply_create
        end
      end
  	end
  	resources :tags, only: [:create,:destroy,:edit]
  	resources :messages, only: [:create,:new]
  	resources :rooms, only: [:create,:index,:show]




  namespace :admins do
  	get 'tops' => 'tops#top'
  	#adminのTopページ↑
  	get 'searches/search' => 'searches#search'

  	resources :tags, only: [:index,:destroy]
  	resources :users, only: [:show,:index,:edit,:update,:destroy] do
  		member do
  			get :following, :followers ,:favorite_index
  		end
    end
	 resources :relationships, only: [:create,:destroy]
	 resources :posts, only: [:index,:show,:edit,:update,:destroy] do
      member do
        get :tag_post_index, :favorite_user_index
      end
	  	resources :favorites, only: [:show,:index]
	  	resources :comments, only: [:destroy]
	  end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :comment_to_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  #DM
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

# follow機能
  has_many :following_relationships, foreign_key: "follower_id", class_name:"Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name:"Relationship", dependent: :destroy

  has_many :followers, through: :follower_relationships


# block機能

  has_many :blocking_block_relationships, foreign_key: "blocked_id", class_name:"BlockRelationship", dependent: :destroy

  has_many :blockings, through: :blocking_block_relationships

  has_many :blocked_block_relationships, foreign_key: "blocking_id", class_name:"BlockRelationship", dependent: :destroy

  has_many :blockeds, through: :blocked_block_relationships


# 検索機能

   def self.search(search)
      return User.all unless search
      User.where(['name LIKE ?', "%#{search}%"])
    end

# follow機能

  def following?(other_user)
  	following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
  	following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
  	following_relationships.find_by(following_id: other_user.id).destroy
  end

# block機能

  def blocking?(other_user)
    blocking_block_relationships.find_by(blocking_id: other_user.id)
  end

  def block!(other_user)
    blocking_block_relationships.create!(blocking_id: other_user.id)
  end

  def unblock!(other_user)
    blocking_block_relationships.find_by(blocking_id: other_user.id).destroy
  end

# バリデーション
  validates :name, presence: true
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

	PER = 15

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.all
	end

	def index
		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "You have updated User_infomation successfully."
      		redirect_to admins_users_path
      	else
      		render :edit
      	end
	end

	def favorite_index
		@user = User.find(params[:id])
		@posts = @user.favorited_posts.page(params[:page]).per(PER)
	end


	def following
		@user = User.find(params[:id])
		@users = @user.followings
		render "show_follow"
	end

	def followers
		user  = User.find(params[:id])
    	@users = @user.followers
    	render 'show_follower'
	end


	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to admins_users_path
		else
			redirect_to admins_tops_path
		end
	end

	private
	def user_params
		params.require(:user).permit(:name,:email)
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController
end

app/controllers/users/searchs_controller.rb
class Users::SearchsController < ApplicationController

	def search_tag
	end

	def search_post
	end

	def search_user
	end

	def search
	end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  def after_sign_out_path_for(resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_user!

	PER = 15


	def show
		@user = User.find(params[:id])
		@users =  @user.blockings
		@posts = @user.posts.page(params[:page]).per(PER)
		@comments = Comment.all
		# DM
		@currentUserEntry = Entry.where(user_id: current_user.id)
	    @userEntry = Entry.where(user_id: @user.id)
	    if @user.id == current_user.id
	    else
	      @currentUserEntry.each do |cu|
	        @userEntry.each do |u|
	          if cu.room_id == u.room_id then
	            @isRoom = true
	            @roomId = cu.room_id
	          end
	        end
	      end
	      if @isRoom
	      else
	        @room = Room.new
	        @entry = Entry.new
	      end
	    end
	end


	def mypage
		@user = User.find(params[:id])
		@posts = @user.posts.page(params[:page]).per(PER)
		@comments = Comment.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "You have updated User_infomation successfully."
      		redirect_to mypage_user_path(current_user.id)
      	else
      		render :edit
      	end

	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			redirect_to root_path
		end
	end

	# Block機能

	def blocking
		@user = User.find(params[:id])
		@users = @user.blockings
		render "show_block"
	end

	def blockeds
		@user = User.find(params[:id])
		@users = @user.blockeds
		render "show_blocker"
	end

	def block_index
		@user = current_user
		@users = @user.blockings
	end


# UserがいいねしているPostの一覧
	def favorite_index
		@user = User.find(params[:id])
		@posts = @user.favorited_posts.page(params[:page]).per(PER)
	end


# フォロー機能
	def following
		@user = User.find(params[:id])
		@users = @user.followings
		render "show_follow"
	end

	def followers
		@user  = User.find(params[:id])
    	@users = @user.followers
    	render 'show_follower'
	end

	private
	def user_params
		params.require(:user).permit(:name,:email)
	end

end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/comment_to_comments_helper.rb
module Users::CommentToCommentsHelper
end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/helpers/users/favorites_helper.rb
module Users::FavoritesHelper
end

app/helpers/users/messages_helper.rb
module Users::MessagesHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/relationships_helper.rb
module Users::RelationshipsHelper
end

app/helpers/users/rooms_helper.rb
module Users::RoomsHelper
end

app/helpers/users/searchs_helper.rb
module Users::SearchsHelper
end

app/views/admins/users/_stats.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <% @user ||= current_user %>
      <div class="stats">
        <a href=<%= following_admins_user_path(@user) %>>
          <strong id="following" class="stat">
            <%= @user.followings.count %>
          </strong>
          following
        </a>
        <a href=<%= followers_admins_user_path(@user) %>>
          <strong id="followers" class="stat">
            <%= @user.followers.count %>
          </strong>
          followers
        </a>
      </div>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/admins/users/edit.html.erb
<%= render "layouts/admin_header"%>
<div class="container">
	<h1>プロフィール編集</h1>
	<div class="main">
		<div class="end-user-edit-form">
    		<table class="end-user-edit-table">
    			<%= form_for(@user, url:  admins_user_path) do |f| %>
    			<tr><td><label>Name</label><br>
    				<%= f.text_field :name ,placeholder:"田中建造"%>
    			</td></tr>
    			<tr><td><label>Email</label><br>
    				<%= f.text_field :email ,placeholder:"sample@icloud.com"%>
    			</td></tr>

    			<tr><td><%= f.submit "Update"%></td></tr>
    		      <% end %>
    		</table>
		</div>
	</div>
</div>

app/views/admins/users/favorite_index.html.erb
<%= render "layouts/admin_header"%>
<div class="container">
	<div class="all_posttitle"><h2>Favorite Index</h2></div>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<% @posts.each do |post| %>
				<div class="bbox wrapper">
					<div class="nametitletag">
						<div class="name"><label>name</label>  /
								<%= link_to "#{post.user.name}",  admins_user_path(post.user) %><br>
						</div>
						<div class="title"><label>title</label>  /  <%= link_to post.title,   admins_post_path(post.id) %></div>
						<div class="tags"><label>tags</label>
							<p>
								<% post.tags.each do |tag| %>
								<%= link_to tag.tag, tag_post_index_admins_post_path(tag.id) %>
								<% end %>
							</p>
						</div>
					</div>
					<div class="timesection">
						いいね件数: <%= post.favorites.count %><br>
						<%= post.comment.count %>件コメント<br>
						by<%= link_to "#{post.user.name}", admins_post_path(post.user) %><br>
						<%= post.created_at.strftime('%Y/%m/%d') %><br>
						<%= link_to "投稿削除" , admins_post_path(post) ,method: :delete, data: {confirm: '本当に削除しますか？'} %>
					</div>
				</div>
			<% end %>
		</div>
		<div class="col-md-2"></div>
	</div>
	<div class="row">
		<%= paginate @posts -%>
	</div>
</div>

app/views/admins/users/index.html.erb
<%= render "layouts/admin_header"%>
<div class="container">
	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<table class="table table-striped">
				<tr>
					<td>名前</td>
					<td>メールアドレス</td>
					<td>登録日</td>
					<td></td>
					<td></td>
				</tr>
				<% @users.each do |user| %>
				<tr>
					 <!-- ,class: "glyphicon", style:"padding-top:15px;"@admin_header -->
						<td><%=link_to "#{user.name}", admins_user_path(user)%></td>
						<td><%=user.email%></td>
						<td><%= user.created_at.strftime('%Y/%m/%d') %></td>
						<td><%=link_to "編集", edit_admins_user_path(user),data: {"turbolinks" => false}%></td>
						<td><%=link_to "削除",   admins_user_path(user), method: :delete , data: {confirm: '本当に消去しますか？'} %></td>
				</tr>
				<% end %>
			</table>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>

app/views/admins/users/show.html.erb
<%= render "layouts/admin_header"%>
<div class="container">
	<div class="row">
		<h1><%= @user.name %></h1>
		<div class="col-lg-12 main">
			<table class="information">
				<tr>
					<th>Name</th><td><%= @user.name %></td>
				</tr>
				<tr>
					<th>Email</th><td><%= @user.email%></td>
				</tr>
			</table>
		</div>
	</div>

	<div class="row">
		<div class="status"><%= render 'stats' %></div>
	</div>

	<div class="row prof">
		<div class="col-lg-5"><%= link_to "Favorite index" ,  favorite_index_admins_user_path(@user.id) ,class:"btn btn-success" %></div>
		<div class="col-lg-4"><%= link_to "プロフィール編集" , edit_admins_user_path(@user) ,class:"btn btn-success" %></div>
		<div class="col-lg-3"><%= link_to "User消去" , admins_user_path(@user) ,class:"btn btn-danger", method: :delete, data: {confirm: '本当に消去しますか？'} %></div>
	</div>
	<div class="row">
		<h1> 投稿一覧</h1>
		<% @posts.reverse.each do |post|%>
			<div class="box wrapper">
				<div class="nametitletag">
					<div class="name"><label>name</label>  /  <%= link_to @user.name,  admins_user_path(@user.id) %></div>
					<div class="title"><label>title</label>  /  <%= link_to post.title,  admins_post_path(post.id) %></div>
					<div class="tags"><label>tags</label>
						<p>
							<% post.tags.each do |tag| %>
							<%= link_to tag.tag, tag_post_index_admins_post_path(tag.id) %>
							<% end %>
						</p>
					</div>
				</div>
				<div class="timesection">
					<!-- コメント総数、いいね総数、By.User名 timestamo -->
					いいね件数: <%= post.favorites.count %><br>
					<%= post.comment.count %>件コメント<br>
					by<%= link_to "#{post.user.name}", admins_user_path(@user) %><br>
					<%= post.created_at.strftime('%Y/%m/%d') %><br>
					<%= link_to "投稿削除" , admins_post_path(post) ,method: :delete, data: {confirm: '本当に削除しますか？'} %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/admins/users/show_follow.html.erb
<%= render "layouts/admin_header"%>
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
    <% @user.followings.each do |user| %>
      <div class="user_favorite_index">
        <div class="username">
          <%= link_to "#{user.name}", admins_user_path(user) %>
        </div>
      </div>
    <% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

app/views/admins/users/show_follower.html.erb
<%= render "layouts/admin_header"%>
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
    <% @user.followers.each do |user| %>
    	<div class="user_favorite_index">
        <div class="username">
		      <%= link_to "#{user.name}", admins_user_path(user) %>
        </div>
      </div>
		<% end %>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>