config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
 sessions:      'admins/sessions',
 passwords:     'admins/passwords',
 registrations: 'admins/registrations'
 }
 devise_for :users, controllers: {
 sessions:      'users/sessions',
 passwords:     'users/passwords',
 registrations: 'users/registrations'
 }

  root 'tops#top'
  get 'tops/all_top' => 'tops#all_top'
  get 'tops/about' => 'tops#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only: [:show,:edit,:update,:destroy] do
  	member do
  		get :following, :followers, :mypage, :favorite_index, :blockeds, :blocking, :block_index
  	end
  end
  	resources :relationships, only: [:create,:destroy]
    resources :block_relationships, only: [:create,:destroy]
  	get 'tops/follow_top' => 'tops#follow_top'
  	get 'searches/search' => 'searches#search'
  	resources :posts, only: [:show,:edit,:new,:update,:create,:destroy] do
      member do
        get :tag_post_index, :favorite_user_index
      end
  		resources :favorites, only: [:create,:destroy]
  		resources :comments, only: [:create,:new,:destroy] do
        member do
          get :reply
          post :reply_create
        end
      end
  	end
  	resources :tags, only: [:create,:destroy,:edit]
  	resources :messages, only: [:create,:new]
  	resources :rooms, only: [:create,:index,:show]




  namespace :admins do
  	get 'tops' => 'tops#top'
  	#adminのTopページ↑
  	get 'searches/search' => 'searches#search'

  	resources :tags, only: [:index,:destroy]
  	resources :users, only: [:show,:index,:edit,:update,:destroy] do
  		member do
  			get :following, :followers ,:favorite_index
  		end
    end
	 resources :relationships, only: [:create,:destroy]
	 resources :posts, only: [:index,:show,:edit,:update,:destroy] do
      member do
        get :tag_post_index, :favorite_user_index
      end
	  	resources :favorites, only: [:show,:index]
	  	resources :comments, only: [:destroy]
	  end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block_relationship.rb
class BlockRelationship < ApplicationRecord
	belongs_to :blocking, class_name: "User"
	belongs_to :blocked, class_name: "User"
	validates :blocking_id, presence: true
	validates :blocked_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	has_many :comment_to_comments

	belongs_to :user
end

app/models/entry.rb
class Entry < ApplicationRecord

	belongs_to :user
	belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :post, counter_cache: :likes_count
	validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord


	 def self.search(search)
      if search
        Post.where(['title LIKE ?', "%#{search}%"])
      else
        Post.all
      end
    end

	belongs_to :user , optional: true

	has_many :comment, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	has_many :post_tags
	has_many :tags, through: :post_tags

	validates :title, presence: true

	def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end

	accepts_nested_attributes_for :tags, allow_destroy: true
end

app/models/post_tag.rb
class PostTag < ApplicationRecord


	belongs_to :tag
	belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"
	validates :following_id, presence: true
	validates :follower_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord

	has_many :messages, dependent: :destroy
	has_many :entries, dependent: :destroy
	has_many :users, through: :entries
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord


	 def self.search(search)
      return Tag.all unless search
      Tag.where(['tag LIKE ?', "%#{search}%"])
    end

	has_many :post_tags
	has_many :posts, through: :post_tags
	has_many :chated_posts, through: :post_tags, source: :post
	validates :tag,uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :comment_to_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  #DM
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

# follow機能
  has_many :following_relationships, foreign_key: "follower_id", class_name:"Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships

  has_many :follower_relationships, foreign_key: "following_id", class_name:"Relationship", dependent: :destroy

  has_many :followers, through: :follower_relationships


# block機能

  has_many :blocking_block_relationships, foreign_key: "blocked_id", class_name:"BlockRelationship", dependent: :destroy

  has_many :blockings, through: :blocking_block_relationships

  has_many :blocked_block_relationships, foreign_key: "blocking_id", class_name:"BlockRelationship", dependent: :destroy

  has_many :blockeds, through: :blocked_block_relationships


# 検索機能

   def self.search(search)
      return User.all unless search
      User.where(['name LIKE ?', "%#{search}%"])
    end

# follow機能

  def following?(other_user)
  	following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
  	following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
  	following_relationships.find_by(following_id: other_user.id).destroy
  end

# block機能

  def blocking?(other_user)
    blocking_block_relationships.find_by(blocking_id: other_user.id)
  end

  def block!(other_user)
    blocking_block_relationships.create!(blocking_id: other_user.id)
  end

  def unblock!(other_user)
    blocking_block_relationships.find_by(blocking_id: other_user.id).destroy
  end

# バリデーション
  validates :name, presence: true
end

app/controllers/admins/searches_controller.rb
class Admins::SearchesController < ApplicationController

	def search
		@number = params[:number]
		@search = params[:content]
		@result = 0
		case @number
		when "1"
			@result = User.search(@search)
			render :search
		when "2"
			@result = Tag.search(@search).page(params[:page]).per(PER)
			render :search

		when "3"
			@result = Post.search(@search).page(params[:page]).per(PER)
			render :search
		end
	end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController


	PER = 15


	def search
		@number = params[:number]
		@search = params[:content]
		@result = 0
		case @number
		when "1"
			@result = User.search(@search).page(params[:page]).per(PER)
			render :search
		when "2"
			@result = Tag.search(@search).page(params[:page]).per(PER)
			render :search

		when "3"
			@result = Post.search(@search).page(params[:page]).per(PER)
			render :search
		end
	end
end

app/controllers/users/searchs_controller.rb
class Users::SearchsController < ApplicationController

	def search_tag
	end

	def search_post
	end

	def search_user
	end

	def search
	end
end

app/helpers/admins/searches_helper.rb
module Admins::SearchesHelper
end

app/helpers/admins/searchs_helper.rb
module Admins::SearchsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users/searchs_helper.rb
module Users::SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def current_user?(user)
    	user == current_user
	end
end

app/views/searches/search.html.erb
<%= render "layouts/user_header"%>

<% if @number == "1" %>
	<div class="container">
		<div class="row">
			<h1><%= @result.name %></h1>
			<div class="col-md-3"></div>
			<div class="col-md-6">
				<% @result.each do |user| %>
				<div class="user_favorite_index">
					<div class="username">
						<% if current_user == user %>
							<%= link_to "#{user.name}", mypage_user_path(current_user) %>
						<% else %>
							<%= link_to "#{user.name}", user_path(user) %>
						<% end %>
					</div>
				</div>
				<% end %>
			</div>
			<div class="col-md-3"></div>
		</div>
	</div>
<% elsif @number == "2" %>
	<div class="container">
		<div class="all_posttitle"><h2><%= @search %></h2></div>
			<div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<% @result.reverse_each do |tag| %>
						<% tag.posts.each do |post| %>
							<div class="bbox wrapper">
								<div class="nametitletag">
									<div class="name"><label>name</label>  / 
										<% if current_user == post.user %>
											<%= link_to "#{post.user.name}", mypage_user_path(current_user) %><br>
										<% else %>
											<%= link_to "#{post.user.name}", user_path(post.user) %><br>
										<% end %>
									</div>
									<div class="title"><label>title</label>  /  <%= link_to post.title,  post_path(post.id) %></div>
									<div class="tags">
										<label>tags</label>
										<p>
											<% post.tags.each do |tag| %>
											<%= link_to tag.tag, tag_post_index_post_path(tag.id) %>
											<% end %>
										</p>
									</div>
								</div>
								<div class="timesection">
									いいね件数: <%= post.favorites.count %><br>
									<%= post.comment.count %>件コメント<br>
									<% if current_user == post.user %>
										by<%= link_to "#{post.user.name}", mypage_user_path(current_user) %><br>
									<% else %>
										by<%= link_to "#{post.user.name}", user_path(post.user) %><br>
									<% end %>
									<%= post.created_at.strftime('%Y/%m/%d') %>
								</div>
							</div>
						<% end %>
					<% end %>
				</div>
				<div class="col-md-2"></div>
		</div>
		<div class="row">
			<%= paginate @result -%>
		</div>
	</div>
<% elsif @number == "3"%>
	<div class="container">
		<div class="all_posttitle"><h2><%= @search %></h2></div>
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
				<% @result.reverse_each do |post| %>
				<div class="bbox wrapper">
					<div class="nametitletag">
						<div class="name"><label>name</label>  / 
							<% if current_user == post.user %>
								<%= link_to "#{post.user.name}", mypage_user_path(current_user) %><br>
							<% else %>
								<%= link_to "#{post.user.name}", user_path(post.user) %><br>
							<% end %>
						</div>
						<div class="title"><label>title</label>  /  <%= link_to post.title,  post_path(post.id) %></div>
						<div class="tags">
							<label>tags</label>
							<p>
								<% post.tags.each do |tag| %>
								<%= link_to tag.tag, tag_post_index_post_path(tag.id) %>
								<% end %>
							</p>
						</div>
					</div>
					<div class="timesection">
						いいね件数: <%= post.favorites.count %><br>
						<%= post.comment.count %>件コメント<br>
						<% if current_user == post.user %>
							by<%= link_to "#{post.user.name}", mypage_user_path(current_user) %><br>
						<% else %>
							by<%= link_to "#{post.user.name}", user_path(post.user) %><br>
						<% end %>
						<%= post.created_at.strftime('%Y/%m/%d') %>
					</div>
				</div>
				<% end %>
			</div>
			<div class="col-md-2"></div>
		</div>
		<div class="row">
			<%= paginate @result -%>
		</div>
	</div>
<% else %>
  検索できませんでした。
<%end%>