config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
 sessions:      'admins/sessions',
 passwords:     'admins/passwords',
 registrations: 'admins/registrations'
 }
 devise_for :users, controllers: {
 sessions:      'users/sessions',
 passwords:     'users/passwords',
 registrations: 'users/registrations'
 }

  root 'tops#top'
  get 'tops/all_top' => 'tops#all_top'
  get 'tops/about' => 'tops#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :users, only: [:show,:edit,:update,:destroy] do
  	member do
  		get :following, :followers, :mypage, :favorite_index, :blockeds, :blocking, :block_index
  	end
  end
  	resources :relationships, only: [:create,:destroy]
    resources :block_relationships, only: [:create,:destroy]
  	get 'tops/follow_top' => 'tops#follow_top'
  	get 'searches/search' => 'searches#search'
  	resources :posts, only: [:show,:edit,:new,:update,:create,:destroy] do
      member do
        get :tag_post_index, :favorite_user_index
      end
  		resources :favorites, only: [:create,:destroy]
  		resources :comments, only: [:create,:new,:destroy] do
        member do
          get :reply
          post :reply_create
        end
      end
  	end
  	resources :tags, only: [:create,:destroy,:edit]
  	resources :messages, only: [:create,:new]
  	resources :rooms, only: [:create,:index,:show]




  namespace :admins do
  	get 'tops' => 'tops#top'
  	#adminのTopページ↑
  	get 'searches/search' => 'searches#search'

  	resources :tags, only: [:index,:destroy]
  	resources :users, only: [:show,:index,:edit,:update,:destroy] do
  		member do
  			get :following, :followers ,:favorite_index
  		end
    end
	 resources :relationships, only: [:create,:destroy]
	 resources :posts, only: [:index,:show,:edit,:update,:destroy] do
      member do
        get :tag_post_index, :favorite_user_index
      end
	  	resources :favorites, only: [:show,:index]
	  	resources :comments, only: [:destroy]
	  end
  end

end

app/models/post.rb
class Post < ApplicationRecord


	 def self.search(search)
      if search
        Post.where(['title LIKE ?', "%#{search}%"])
      else
        Post.all
      end
    end

	belongs_to :user , optional: true

	has_many :comment, dependent: :destroy
	has_many :favorites, dependent: :destroy
	has_many :favorited_users, through: :favorites, source: :user
	has_many :post_tags
	has_many :tags, through: :post_tags

	validates :title, presence: true

	def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end

	accepts_nested_attributes_for :tags, allow_destroy: true
end

app/controllers/admins/posts_controller.rb
class Admins::PostsController < ApplicationController


	PER = 15


	def show
		@post = Post.find(params[:id])
		@favorite = Favorite.where(post_id: @post.id)
		@comments = Comment.where(post_id: @post.id)
		@user = @post.user
	end

	def index
		@posts = Post.all.page(params[:page]).per(PER)
	end

	def edit
		# 時間があれば
	end

	def update
		#時間があれば
	end

	def tag_post_index
		@tag = Tag.find(params[:id])
		@posts = @tag.chated_posts
	end

	def favorite_user_index
		@post = Post.find(params[:id])
		@users = @post.favorited_users
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.destroy
			redirect_to admins_tags_path
		else
			redirect_to admins_user_path
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!

	PER = 15


	def show
		@post = Post.find(params[:id])
		@favorite = Favorite.where(post_id: @post.id, user_id: current_user.id)
		@comments = Comment.where(post_id: @post.id)
		@user = @post.user
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		number = 1
		if @post.save
			puts tag_params
			tag_params[:tags_attributes]
			if params[:post][:tags_attributes]
				params[:post][:tags_attributes].each do |post_tag|
					@tag = Tag.find_or_create_by(tag: post_tag[1][:tag])
					PostTag.create(post_id:@post.id, tag_id: @tag.id)
				end
			end

				redirect_to mypage_user_path(current_user.id)
		else
			render :new
		end
	end


# Tagが持つPost一覧
	def tag_post_index
		@tag = Tag.find(params[:id])
		@posts = @tag.chated_posts.page(params[:page]).per(PER)
	end

# いいねしたUser一覧
	def favorite_user_index
		@post = Post.find(params[:id])
		@users = @post.favorited_users
	end


	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
		if @post.user_id == current_user

		else
			redirect_to root_path
		end
	end



	def update
		#@post = Post.find(params[:id])
		#@post.user_id = current_user.id 時間があれば
	end

	def destroy
		@post = Post.find(params[:id])
		if @post.destroy
			redirect_to mypage_user_path(current_user.id)
		else
			redirect_to mypage_user_path(current_user.id)
		end
	end

	private
	def post_params
		params.require(:post).permit(:title)
	end

	def tag_params
		params.require(:post)
	end
end

app/helpers/admins/posts_helper.rb
module Admins::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/views/posts/_tag_fields.html.erb
<div class="container">
	<div class="nested-fields">
		<div class="nested-fields-tags">
		<div>tags</div>
		<%= f.text_field :tag %>
		<%= link_to_remove_association "remove tags", f ,class: 'btn btn-danger'%><br>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<%= render "layouts/user_header"%>

<div class="container">
	<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <h1>Post作成画面</h1>
    <div class="main-new">
    	<%= form_with(model: Post.new, url: user_posts_path, local:true) do |f| %>
    	<div class="field">
    		<!-- title -->
    		<h2>title</h2>
    		<%= f.text_field :title %><br>
    	</div>

    	<h2>Tag</h2>

    	<%= f.fields_for :tags do |tag| %>
    	<div class="tag">
    		<%= render 'tag_fields', f:  tag %>
    	</div>
    	<% end %>
    	<div class="links">
    		<%= link_to_add_association 'Tag追加', f,:tags %>
    	</div>

        <%= f.submit '投稿' %>
        <% end %>
    </div>
</div>

app/views/posts/favorite_user_index.html.erb
<%= render "layouts/user_header"%>
<div class="container">
	<div class="row">
		<h1>いいねしているUser</h1>
		<div class="col-md-3"></div>
		<div class="col-md-6">
			<% @users.each do |user| %>
			<div class="user_favorite_index">
				<div class="username">
					<% if current_user == user %>
						<%= link_to "#{user.name}", mypage_user_path(current_user) %>
					<% else %>
						<%= link_to "#{user.name}", user_path(user) %>
					<% end %>
				</div>
			</div>
			<% end %>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>

app/views/posts/new.html.erb
<%= render "layouts/user_header"%>

<div class="container">

    <h1>Post作成画面</h1>

    <div class="main-new">
    	<%= form_with(model: Post.new, url: posts_path, local:true) do |f| %>
    	<div class="field">
    		<!-- title -->
    		<h2>title</h2>
    		<%= f.text_field :title %><br>
    	</div>

    	<h2>Tag</h2>

    	<%= f.fields_for :tags do |tag| %>

    	<div class="tag">
    		<%= render 'tag_fields', f:  tag %>
    	</div>
    	<% end %>
    	<div class="links">
    		<%= link_to_add_association 'Tag追加', f,:tags %>
    	</div>
        <%= f.submit '投稿' %>
        <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<%= render "layouts/user_header"%>
<div class="container containerpost">
	<div class="row posttitle border">
		<div class="col-md-10">
			<h1><%= @post.title %></h1>
		</div>
		<div class="col-md-2">
			<!-- ここに情報全部 -->
			いいね件数: <%= link_to @post.favorites.count ,favorite_user_index_post_path%>
			<%= render 'layouts/favorites', post: @post ,favorite: @favorite %>
			<%= @comments.count %>件コメント<br>
				<% if current_user == @user %>
					by<%= link_to "#{@post.user.name}", mypage_user_path(current_user) %><br>
				<% else %>
					by<%= link_to "#{@post.user.name}", user_path(@user) %><br>
				<% end %>
			<%= @post.created_at.strftime('%Y/%m/%d') %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3 tagcolor">
			<!-- tag一覧 -->
			<% @post.tags.each do |tag| %>
				#<%= link_to tag.tag ,tag_post_index_post_path(tag.id) %><br>
			<% end %>
		</div>
		<div class="col-md-9 commentcolor">
			<!-- コメント -->
			<% @comments.each do |comment|%>
			<!-- コメント内容 -->
			<div class="commentbox wrapper">
				<div class="number"> <%= comment.number %></div>
				<div class="replynumber"><% if comment.reply %>>><%= comment.reply %><% end %></div>
				<div class="commenttext"> <%= comment.comment %></div>
				<div class="information">
					<% if current_user == comment.user %>
						by<%= link_to "#{comment.user.name}", mypage_user_path(current_user) %><br>
					<% else %>
						by<%= link_to "#{comment.user.name}", user_path(comment.user) %><br>
					<% end %>
					<%= comment.created_at.strftime('%Y/%m/%d') %><br>
					<%= link_to "このコメントに対して" ,reply_post_comment_path(@post ,comment.id) %><br>
					<% if current_user == comment.user %>
							<%= link_to "削除",post_comment_path(@post ,comment.id), method: :delete,date:{ confirm:"本当に削除しますか？"} %>
					<% end %>
				</div>
			</div>
			<% end %>
			<!-- 丸 -->
			<%= link_to new_post_comment_path(@post.id) do %>
				<div class="commentpost">+</div>
			<% end %>
		</div>
	</div>
</div>

app/views/posts/tag_post_index.html.erb
<%= render "layouts/user_header"%>
<div class="container">
	<div class="all_posttitle"><h2><%= @tag.tag %></h2></div>
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-8">
			<% @posts.reverse_each do |post| %>
				<div class="bbox wrapper">
					<div class="nametitletag">
						<div class="name"><label>name</label>  / 
							<% if current_user == post.user %>
								<%= link_to "#{post.user.name}", mypage_user_path(current_user) %><br>
							<% else %>
								<%= link_to "#{post.user.name}", user_path(post.user) %><br>
							<% end %>
						</div>
						<div class="title"><label>title</label>  /  <%= link_to post.title,  post_path(post.id) %></div>
						<div class="tags"><label>tags</label>
							<p>
								<% post.tags.each do |tag| %>
								<%= link_to tag.tag, tag_post_index_post_path(tag.id) %>
								<% end %>
							</p>
						</div>
					</div>
					<div class="timesection">
						いいね件数: <%= post.favorites.count %><br>
						<%= post.comment.count %>件コメント<br>
						<% if current_user == post.user %>
							by<%= link_to "#{post.user.name}", mypage_user_path(current_user) %><br>
						<% else %>
							by<%= link_to "#{post.user.name}", user_path(post.user) %><br>
						<% end %>
						<%= post.created_at.strftime('%Y/%m/%d') %>
					</div>
				</div>
			<% end %>
		</div>
		<div class="col-md-2"></div>
	</div>
	<div class="row">
		<%= paginate @posts -%>
	</div>
</div>